name: Build qc_image_unpacker

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make gcc
      run: ./make.sh gcc
    - name: make clang
      run: ./make.sh clang
